[package]
name = "kernel"
version = "0.1.0"
authors = ["ChenRuiwei <1982833213@qq.com>"]
edition = "2021"

[dependencies]
config = { path = "../lib/config/" }
log = "0.4.20"
riscv-rt = "0.12.2"
spin = "0.9.8"
buddy_system_allocator = "0.9.1"
sbi-rt = { version = "0.0.3", features = ["legacy"] }
riscv = "0.11.1"

[build-dependencies]
config = { path = "../lib/config/" }
