[package]
name = "kernel"
version = "0.1.0"
authors = ["ChenRuiwei <1982833213@qq.com>"]
edition = "2021"

[dependencies]
arch = { path = "../arch" }
config = { path = "../config" }
sync = { path = "../modules/sync/" }

log = "0.4"
riscv-rt = "0.12"
spin = "0.9"
buddy_system_allocator = "0.9"
sbi-rt = { version = "0.0", features = ["legacy"] }
riscv = "0.11"

[build-dependencies]
config = { path = "../config" }
