./test-ltp.sh ltp/testcases/bin/abs01
./test-ltp.sh ltp/testcases/bin/accept01
./test-ltp.sh /ltp/testcases/bin/accept02
./test-ltp.sh /ltp/testcases/bin/add_key02
./test-ltp.sh /ltp/testcases/bin/add_key04
./test-ltp.sh /ltp/testcases/bin/af_alg02
./test-ltp.sh ltp/testcases/bin/alarm02
./test-ltp.sh ltp/testcases/bin/alarm03
./test-ltp.sh ltp/testcases/bin/alarm05
./test-ltp.sh ltp/testcases/bin/alarm06
./test-ltp.sh ltp/testcases/bin/alarm07
./test-ltp.sh ltp/testcases/bin/atof01
./test-ltp.sh /ltp/testcases/bin/brk01
./test-ltp.sh /ltp/testcases/bin/brk02
./test-ltp.sh /ltp/testcases/bin/capget01
./test-ltp.sh /ltp/testcases/bin/capget02
./test-ltp.sh /ltp/testcases/bin/capset01
./test-ltp.sh /ltp/testcases/bin/capset04
./test-ltp.sh ltp/testcases/bin/chdir04
./test-ltp.sh ltp/testcases/bin/chmod01
./test-ltp.sh ltp/testcases/bin/chown01
./test-ltp.sh ltp/testcases/bin/chown05
./test-ltp.sh ltp/testcases/bin/chroot03
./test-ltp.sh ltp/testcases/bin/clock_getres01
./test-ltp.sh ltp/testcases/bin/clock_gettime02
./test-ltp.sh ltp/testcases/bin/clock_nanosleep04
./test-ltp.sh ltp/testcases/bin/clone01
./test-ltp.sh /ltp/testcases/bin/clone02
./test-ltp.sh /ltp/testcases/bin/clone03
./test-ltp.sh ltp/testcases/bin/clone04
./test-ltp.sh /ltp/testcases/bin/clone05
./test-ltp.sh /ltp/testcases/bin/clone07
./test-ltp.sh ltp/testcases/bin/clone302
./test-ltp.sh ltp/testcases/bin/close01
./test-ltp.sh ltp/testcases/bin/close02
./test-ltp.sh ltp/testcases/bin/confstr01
./test-ltp.sh /ltp/testcases/bin/cpuhotplug_hotplug.sh
./test-ltp.sh /ltp/testcases/bin/cpuhotplug_testsuite.sh
./test-ltp.sh /ltp/testcases/bin/crash01
./test-ltp.sh /ltp/testcases/bin/crash02
./test-ltp.sh ltp/testcases/bin/creat01
./test-ltp.sh ltp/testcases/bin/creat03
./test-ltp.sh ltp/testcases/bin/creat05
./test-ltp.sh /ltp/testcases/bin/daemonlib.sh
./test-ltp.sh ltp/testcases/bin/diotest1
./test-ltp.sh ltp/testcases/bin/diotest3
./test-ltp.sh /ltp/testcases/bin/diotest5
./test-ltp.sh ltp/testcases/bin/diotest6
./test-ltp.sh ltp/testcases/bin/dirty
./test-ltp.sh ltp/testcases/bin/dup01
./test-ltp.sh ltp/testcases/bin/dup02
./test-ltp.sh ltp/testcases/bin/dup03
./test-ltp.sh ltp/testcases/bin/dup04
./test-ltp.sh ltp/testcases/bin/dup06
./test-ltp.sh ltp/testcases/bin/dup07
./test-ltp.sh ltp/testcases/bin/dup201
./test-ltp.sh ltp/testcases/bin/dup202
./test-ltp.sh ltp/testcases/bin/dup203
./test-ltp.sh ltp/testcases/bin/dup204
./test-ltp.sh ltp/testcases/bin/dup205
./test-ltp.sh ltp/testcases/bin/dup206
./test-ltp.sh ltp/testcases/bin/dup207
./test-ltp.sh ltp/testcases/bin/dup3_01
./test-ltp.sh ltp/testcases/bin/dup3_02
./test-ltp.sh ltp/testcases/bin/epoll_create1_02
./test-ltp.sh ltp/testcases/bin/epoll_ctl01
./test-ltp.sh ltp/testcases/bin/epoll_ctl02
./test-ltp.sh /ltp/testcases/bin/epoll_ctl03
./test-ltp.sh ltp/testcases/bin/epoll_ctl04
./test-ltp.sh ltp/testcases/bin/epoll_ctl05
./test-ltp.sh ltp/testcases/bin/epoll_wait01
./test-ltp.sh ltp/testcases/bin/epoll_wait03
./test-ltp.sh ltp/testcases/bin/epoll_wait04
./test-ltp.sh /ltp/testcases/bin/epoll_wait06
./test-ltp.sh ltp/testcases/bin/epoll_wait07
./test-ltp.sh /ltp/testcases/bin/exit01
./test-ltp.sh ltp/testcases/bin/exit02
./test-ltp.sh /ltp/testcases/bin/exit_group01
./test-ltp.sh ltp/testcases/bin/faccessat01
./test-ltp.sh ltp/testcases/bin/faccessat02
./test-ltp.sh /ltp/testcases/bin/fallocate03
./test-ltp.sh /ltp/testcases/bin/fanotify_child
./test-ltp.sh ltp/testcases/bin/fchdir01
./test-ltp.sh ltp/testcases/bin/fchdir02
./test-ltp.sh ltp/testcases/bin/fchmod01
./test-ltp.sh ltp/testcases/bin/fchmodat01
./test-ltp.sh ltp/testcases/bin/fchmodat02
./test-ltp.sh ltp/testcases/bin/fchown01
./test-ltp.sh ltp/testcases/bin/fchown02
./test-ltp.sh ltp/testcases/bin/fcntl02
./test-ltp.sh ltp/testcases/bin/fcntl02_64
./test-ltp.sh ltp/testcases/bin/fcntl03
./test-ltp.sh ltp/testcases/bin/fcntl03_64
./test-ltp.sh ltp/testcases/bin/fcntl04
./test-ltp.sh ltp/testcases/bin/fcntl04_64
./test-ltp.sh ltp/testcases/bin/fcntl05
./test-ltp.sh ltp/testcases/bin/fcntl05_64
./test-ltp.sh ltp/testcases/bin/fcntl08
./test-ltp.sh ltp/testcases/bin/fcntl08_64
./test-ltp.sh /ltp/testcases/bin/fcntl09_64
./test-ltp.sh /ltp/testcases/bin/fcntl10
./test-ltp.sh /ltp/testcases/bin/fcntl10_64
./test-ltp.sh /ltp/testcases/bin/fcntl13
./test-ltp.sh ltp/testcases/bin/fcntl13_64
./test-ltp.sh /ltp/testcases/bin/fcntl16
./test-ltp.sh /ltp/testcases/bin/fcntl16_64
./test-ltp.sh /ltp/testcases/bin/fcntl23
./test-ltp.sh /ltp/testcases/bin/fcntl23_64
./test-ltp.sh ltp/testcases/bin/fcntl27
./test-ltp.sh /ltp/testcases/bin/fcntl27_64
./test-ltp.sh ltp/testcases/bin/fcntl29
./test-ltp.sh ltp/testcases/bin/fcntl29_64
./test-ltp.sh /ltp/testcases/bin/fcntl34
./test-ltp.sh /ltp/testcases/bin/fcntl34_64
./test-ltp.sh /ltp/testcases/bin/fcntl36
./test-ltp.sh /ltp/testcases/bin/fcntl36_64
./test-ltp.sh ltp/testcases/bin/fdatasync02
./test-ltp.sh ltp/testcases/bin/fgetxattr03
./test-ltp.sh ltp/testcases/bin/flock01
./test-ltp.sh /ltp/testcases/bin/flock02
./test-ltp.sh ltp/testcases/bin/flock04
./test-ltp.sh ltp/testcases/bin/flock06
./test-ltp.sh /ltp/testcases/bin/fmtmsg01
./test-ltp.sh ltp/testcases/bin/fork01
./test-ltp.sh ltp/testcases/bin/fork03
./test-ltp.sh ltp/testcases/bin/fork05
./test-ltp.sh ltp/testcases/bin/fork07
./test-ltp.sh ltp/testcases/bin/fork08
./test-ltp.sh ltp/testcases/bin/fork09
./test-ltp.sh ltp/testcases/bin/fork10
./test-ltp.sh ltp/testcases/bin/fork_procs
./test-ltp.sh ltp/testcases/bin/fpathconf01
./test-ltp.sh ltp/testcases/bin/fptest01
./test-ltp.sh ltp/testcases/bin/fptest02
./test-ltp.sh /ltp/testcases/bin/fs_racer.sh
./test-ltp.sh /ltp/testcases/bin/futex_cmp_requeue02
./test-ltp.sh ltp/testcases/bin/futex_wait01
./test-ltp.sh /ltp/testcases/bin/futex_wait02
./test-ltp.sh ltp/testcases/bin/futex_wait03
./test-ltp.sh ltp/testcases/bin/futex_wait04
./test-ltp.sh ltp/testcases/bin/futex_wake01
./test-ltp.sh /ltp/testcases/bin/genacos
./test-ltp.sh /ltp/testcases/bin/genasin
./test-ltp.sh /ltp/testcases/bin/genatan
./test-ltp.sh /ltp/testcases/bin/genatan2
./test-ltp.sh /ltp/testcases/bin/genceil
./test-ltp.sh /ltp/testcases/bin/gencos
./test-ltp.sh /ltp/testcases/bin/gencosh
./test-ltp.sh /ltp/testcases/bin/genexp
./test-ltp.sh /ltp/testcases/bin/genfabs
./test-ltp.sh /ltp/testcases/bin/genfloor
./test-ltp.sh /ltp/testcases/bin/genfmod
./test-ltp.sh /ltp/testcases/bin/genfrexp
./test-ltp.sh /ltp/testcases/bin/genhypot
./test-ltp.sh /ltp/testcases/bin/genj0
./test-ltp.sh /ltp/testcases/bin/genj1
./test-ltp.sh /ltp/testcases/bin/genldexp
./test-ltp.sh /ltp/testcases/bin/genlgamma
./test-ltp.sh /ltp/testcases/bin/genload
./test-ltp.sh /ltp/testcases/bin/genlog
./test-ltp.sh /ltp/testcases/bin/genlog10
./test-ltp.sh /ltp/testcases/bin/genmodf
./test-ltp.sh /ltp/testcases/bin/genpow
./test-ltp.sh /ltp/testcases/bin/gensin
./test-ltp.sh /ltp/testcases/bin/gensinh
./test-ltp.sh /ltp/testcases/bin/gensqrt
./test-ltp.sh /ltp/testcases/bin/gentan
./test-ltp.sh /ltp/testcases/bin/gentanh
./test-ltp.sh /ltp/testcases/bin/geny0
./test-ltp.sh /ltp/testcases/bin/geny1
./test-ltp.sh ltp/testcases/bin/getcontext01
./test-ltp.sh ltp/testcases/bin/getcwd01
./test-ltp.sh ltp/testcases/bin/getcwd02
./test-ltp.sh ltp/testcases/bin/getdomainname01
./test-ltp.sh ltp/testcases/bin/geteuid01
./test-ltp.sh ltp/testcases/bin/gethostbyname_r01
./test-ltp.sh ltp/testcases/bin/gethostname01
./test-ltp.sh ltp/testcases/bin/gethostname02
./test-ltp.sh ltp/testcases/bin/getitimer01
./test-ltp.sh ltp/testcases/bin/getitimer02
./test-ltp.sh ltp/testcases/bin/getpagesize01
./test-ltp.sh ltp/testcases/bin/getpeername01
./test-ltp.sh ltp/testcases/bin/getpgid02
./test-ltp.sh ltp/testcases/bin/getpgrp01
./test-ltp.sh /ltp/testcases/bin/getpid02
./test-ltp.sh ltp/testcases/bin/getppid01
./test-ltp.sh ltp/testcases/bin/getpriority01
./test-ltp.sh ltp/testcases/bin/getpriority02
./test-ltp.sh ltp/testcases/bin/getrandom01
./test-ltp.sh ltp/testcases/bin/getrandom02
./test-ltp.sh ltp/testcases/bin/getrandom03
./test-ltp.sh ltp/testcases/bin/getrandom04
./test-ltp.sh ltp/testcases/bin/getrandom05
./test-ltp.sh ltp/testcases/bin/getresgid01
./test-ltp.sh ltp/testcases/bin/getrlimit01
./test-ltp.sh ltp/testcases/bin/getrlimit02
./test-ltp.sh ltp/testcases/bin/getrlimit03
./test-ltp.sh ltp/testcases/bin/getrusage01
./test-ltp.sh ltp/testcases/bin/getrusage02
./test-ltp.sh ltp/testcases/bin/getsid02
./test-ltp.sh ltp/testcases/bin/getsockname01
./test-ltp.sh ltp/testcases/bin/getsockopt01
./test-ltp.sh ltp/testcases/bin/gettid02
./test-ltp.sh ltp/testcases/bin/gettimeofday01
./test-ltp.sh ltp/testcases/bin/getuid01
./test-ltp.sh ltp/testcases/bin/growfiles
./test-ltp.sh /ltp/testcases/bin/inode01
./test-ltp.sh ltp/testcases/bin/inotify01
./test-ltp.sh ltp/testcases/bin/inotify04
./test-ltp.sh ltp/testcases/bin/ioctl_ns07
./test-ltp.sh ltp/testcases/bin/ioprio_get01
./test-ltp.sh ltp/testcases/bin/ioprio_set01
./test-ltp.sh ltp/testcases/bin/ioprio_set02
./test-ltp.sh ltp/testcases/bin/ioprio_set03
./test-ltp.sh ltp/testcases/bin/kcmp02
./test-ltp.sh ltp/testcases/bin/keyctl03
./test-ltp.sh ltp/testcases/bin/keyctl04
./test-ltp.sh ltp/testcases/bin/keyctl08
./test-ltp.sh ltp/testcases/bin/kill03
./test-ltp.sh ltp/testcases/bin/kill06
./test-ltp.sh ltp/testcases/bin/kill08
./test-ltp.sh /ltp/testcases/bin/kill09
./test-ltp.sh /ltp/testcases/bin/link02
./test-ltp.sh /ltp/testcases/bin/link05
./test-ltp.sh ltp/testcases/bin/listen01
./test-ltp.sh ltp/testcases/bin/llseek02
./test-ltp.sh ltp/testcases/bin/llseek03
./test-ltp.sh ltp/testcases/bin/locktests
./test-ltp.sh ltp/testcases/bin/lseek01
./test-ltp.sh ltp/testcases/bin/lseek07
./test-ltp.sh ltp/testcases/bin/ltpServer
./test-ltp.sh ltp/testcases/bin/madvise03
./test-ltp.sh ltp/testcases/bin/madvise05
./test-ltp.sh ltp/testcases/bin/madvise10
./test-ltp.sh ltp/testcases/bin/mallinfo01
./test-ltp.sh ltp/testcases/bin/mallinfo02
./test-ltp.sh ltp/testcases/bin/mallopt01
./test-ltp.sh /ltp/testcases/bin/mem02
./test-ltp.sh ltp/testcases/bin/memcmp01
./test-ltp.sh ltp/testcases/bin/memcpy01
./test-ltp.sh ltp/testcases/bin/memset01
./test-ltp.sh ltp/testcases/bin/mincore02
./test-ltp.sh ltp/testcases/bin/mincore03
./test-ltp.sh ltp/testcases/bin/mincore04
./test-ltp.sh ltp/testcases/bin/mkdir04
./test-ltp.sh ltp/testcases/bin/mkdirat01
./test-ltp.sh ltp/testcases/bin/mknod09
./test-ltp.sh ltp/testcases/bin/mlock01
./test-ltp.sh ltp/testcases/bin/mlock04
./test-ltp.sh ltp/testcases/bin/mlockall01
./test-ltp.sh ltp/testcases/bin/mmap01
./test-ltp.sh ltp/testcases/bin/mmap02
./test-ltp.sh ltp/testcases/bin/mmap06
./test-ltp.sh ltp/testcases/bin/mmap08
./test-ltp.sh /ltp/testcases/bin/mmap10
./test-ltp.sh ltp/testcases/bin/mmap11
./test-ltp.sh ltp/testcases/bin/mmap17
./test-ltp.sh ltp/testcases/bin/mmap18
./test-ltp.sh ltp/testcases/bin/mmap19
./test-ltp.sh ltp/testcases/bin/mmap2
./test-ltp.sh ltp/testcases/bin/mmap20
./test-ltp.sh ltp/testcases/bin/mmapstress04
./test-ltp.sh ltp/testcases/bin/mmstress_dummy
./test-ltp.sh ltp/testcases/bin/modify_ldt01
./test-ltp.sh ltp/testcases/bin/modify_ldt02
./test-ltp.sh ltp/testcases/bin/modify_ldt03
./test-ltp.sh /ltp/testcases/bin/mprotect02
./test-ltp.sh /ltp/testcases/bin/mprotect03
./test-ltp.sh /ltp/testcases/bin/mprotect04
./test-ltp.sh ltp/testcases/bin/mq_notify02
./test-ltp.sh ltp/testcases/bin/mq_timedreceive01
./test-ltp.sh ltp/testcases/bin/mq_timedsend01
./test-ltp.sh ltp/testcases/bin/msgctl01
./test-ltp.sh ltp/testcases/bin/msgctl02
./test-ltp.sh ltp/testcases/bin/msgctl03
./test-ltp.sh ltp/testcases/bin/msgctl12
./test-ltp.sh ltp/testcases/bin/msgget01
./test-ltp.sh ltp/testcases/bin/msgrcv07
./test-ltp.sh ltp/testcases/bin/msgrcv08
./test-ltp.sh ltp/testcases/bin/msync01
./test-ltp.sh ltp/testcases/bin/msync02
./test-ltp.sh ltp/testcases/bin/munlock01
./test-ltp.sh ltp/testcases/bin/munlock02
./test-ltp.sh /ltp/testcases/bin/munmap01
./test-ltp.sh /ltp/testcases/bin/munmap02
./test-ltp.sh /ltp/testcases/bin/myfunctions.sh
./test-ltp.sh ltp/testcases/bin/name_to_handle_at02
./test-ltp.sh ltp/testcases/bin/newuname01
./test-ltp.sh ltp/testcases/bin/nextafter01
./test-ltp.sh ltp/testcases/bin/nfs05_make_tree
./test-ltp.sh ltp/testcases/bin/nice01
./test-ltp.sh ltp/testcases/bin/nice02
./test-ltp.sh ltp/testcases/bin/open01
./test-ltp.sh ltp/testcases/bin/open03
./test-ltp.sh ltp/testcases/bin/open04
./test-ltp.sh ltp/testcases/bin/open06
./test-ltp.sh /ltp/testcases/bin/open08
./test-ltp.sh ltp/testcases/bin/open09
./test-ltp.sh ltp/testcases/bin/open11
./test-ltp.sh ltp/testcases/bin/openat01
./test-ltp.sh /ltp/testcases/bin/page01
./test-ltp.sh /ltp/testcases/bin/page02
./test-ltp.sh /ltp/testcases/bin/parameters.sh
./test-ltp.sh ltp/testcases/bin/pathconf01
./test-ltp.sh ltp/testcases/bin/personality02
./test-ltp.sh ltp/testcases/bin/pidfd_open03
./test-ltp.sh ltp/testcases/bin/pipe01
./test-ltp.sh ltp/testcases/bin/pipe02
./test-ltp.sh ltp/testcases/bin/pipe03
./test-ltp.sh ltp/testcases/bin/pipe04
./test-ltp.sh ltp/testcases/bin/pipe05
./test-ltp.sh ltp/testcases/bin/pipe06
./test-ltp.sh ltp/testcases/bin/pipe08
./test-ltp.sh ltp/testcases/bin/pipe09
./test-ltp.sh ltp/testcases/bin/pipe14
./test-ltp.sh ltp/testcases/bin/pipe2_01
./test-ltp.sh /ltp/testcases/bin/pm_include.sh
./test-ltp.sh ltp/testcases/bin/poll01
./test-ltp.sh /ltp/testcases/bin/posix_fadvise01
./test-ltp.sh /ltp/testcases/bin/posix_fadvise01_64
./test-ltp.sh ltp/testcases/bin/posix_fadvise02
./test-ltp.sh ltp/testcases/bin/posix_fadvise02_64
./test-ltp.sh /ltp/testcases/bin/posix_fadvise03
./test-ltp.sh /ltp/testcases/bin/posix_fadvise03_64
./test-ltp.sh ltp/testcases/bin/posix_fadvise04
./test-ltp.sh ltp/testcases/bin/posix_fadvise04_64
./test-ltp.sh ltp/testcases/bin/prctl01
./test-ltp.sh ltp/testcases/bin/prctl02
./test-ltp.sh ltp/testcases/bin/prctl03
./test-ltp.sh ltp/testcases/bin/prctl05
./test-ltp.sh ltp/testcases/bin/prctl07
./test-ltp.sh ltp/testcases/bin/prctl08
./test-ltp.sh /ltp/testcases/bin/pread01
./test-ltp.sh /ltp/testcases/bin/pread01_64
./test-ltp.sh ltp/testcases/bin/pread02
./test-ltp.sh ltp/testcases/bin/pread02_64
./test-ltp.sh ltp/testcases/bin/preadv01
./test-ltp.sh ltp/testcases/bin/preadv01_64
./test-ltp.sh ltp/testcases/bin/preadv02
./test-ltp.sh ltp/testcases/bin/preadv02_64
./test-ltp.sh ltp/testcases/bin/preadv201
./test-ltp.sh ltp/testcases/bin/preadv201_64
./test-ltp.sh ltp/testcases/bin/preadv202
./test-ltp.sh ltp/testcases/bin/preadv202_64
./test-ltp.sh ltp/testcases/bin/print_caps
./test-ltp.sh ltp/testcases/bin/proc01
./test-ltp.sh /ltp/testcases/bin/process_vm01
./test-ltp.sh ltp/testcases/bin/pselect03
./test-ltp.sh ltp/testcases/bin/pselect03_64
./test-ltp.sh /ltp/testcases/bin/pth_str02
./test-ltp.sh /ltp/testcases/bin/pwrite01
./test-ltp.sh /ltp/testcases/bin/pwrite01_64
./test-ltp.sh ltp/testcases/bin/pwrite04
./test-ltp.sh ltp/testcases/bin/pwrite04_64
./test-ltp.sh ltp/testcases/bin/pwritev01
./test-ltp.sh ltp/testcases/bin/pwritev01_64
./test-ltp.sh ltp/testcases/bin/pwritev02
./test-ltp.sh ltp/testcases/bin/pwritev02_64
./test-ltp.sh ltp/testcases/bin/pwritev201
./test-ltp.sh ltp/testcases/bin/pwritev201_64
./test-ltp.sh ltp/testcases/bin/pwritev202
./test-ltp.sh ltp/testcases/bin/pwritev202_64
./test-ltp.sh ltp/testcases/bin/read01
./test-ltp.sh ltp/testcases/bin/read02
./test-ltp.sh ltp/testcases/bin/read04
./test-ltp.sh ltp/testcases/bin/readdir01
./test-ltp.sh ltp/testcases/bin/readlinkat02
./test-ltp.sh ltp/testcases/bin/readv01
./test-ltp.sh ltp/testcases/bin/readv02
./test-ltp.sh ltp/testcases/bin/realpath01
./test-ltp.sh ltp/testcases/bin/reboot01
./test-ltp.sh ltp/testcases/bin/recvmmsg01
./test-ltp.sh ltp/testcases/bin/recvmsg02
./test-ltp.sh ltp/testcases/bin/remap_file_pages02
./test-ltp.sh ltp/testcases/bin/rename09
./test-ltp.sh ltp/testcases/bin/request_key01
./test-ltp.sh /ltp/testcases/bin/request_key02
./test-ltp.sh /ltp/testcases/bin/request_key03
./test-ltp.sh ltp/testcases/bin/request_key05
./test-ltp.sh ltp/testcases/bin/rmdir01
./test-ltp.sh ltp/testcases/bin/rpc_auth_destroy
./test-ltp.sh ltp/testcases/bin/rpc_authnone_create
./test-ltp.sh ltp/testcases/bin/rpc_authunix_create
./test-ltp.sh ltp/testcases/bin/rpc_authunix_create_default
./test-ltp.sh ltp/testcases/bin/rpc_callrpc_performance
./test-ltp.sh ltp/testcases/bin/rpc_callrpc_scalability
./test-ltp.sh ltp/testcases/bin/rpc_callrpc_stress
./test-ltp.sh ltp/testcases/bin/rpc_clnt_broadcast_performance
./test-ltp.sh ltp/testcases/bin/rpc_clnt_broadcast_scalability
./test-ltp.sh ltp/testcases/bin/rpc_clnt_broadcast_stress
./test-ltp.sh ltp/testcases/bin/rpc_clnt_destroy_stress
./test-ltp.sh ltp/testcases/bin/rpc_clntraw_create
./test-ltp.sh ltp/testcases/bin/rpc_clntraw_create_performance
./test-ltp.sh ltp/testcases/bin/rpc_svc_destroy
./test-ltp.sh ltp/testcases/bin/rpc_svc_destroy_stress
./test-ltp.sh ltp/testcases/bin/rpc_svcfd_create
./test-ltp.sh ltp/testcases/bin/rpc_svcfd_create_limits
./test-ltp.sh ltp/testcases/bin/rpc_svcraw_create
./test-ltp.sh ltp/testcases/bin/rpc_svcraw_create_performance
./test-ltp.sh /ltp/testcases/bin/rpc_svctcp_create
./test-ltp.sh /ltp/testcases/bin/rpc_svctcp_create_limits
./test-ltp.sh /ltp/testcases/bin/rpc_svctcp_create_performance
./test-ltp.sh /ltp/testcases/bin/rpc_svcudp_bufcreate
./test-ltp.sh /ltp/testcases/bin/rpc_svcudp_bufcreate_limits
./test-ltp.sh /ltp/testcases/bin/rpc_svcudp_create
./test-ltp.sh ltp/testcases/bin/rpc_svcudp_create_performance
./test-ltp.sh ltp/testcases/bin/rpc_xprt_register
./test-ltp.sh ltp/testcases/bin/rpc_xprt_unregister
./test-ltp.sh /ltp/testcases/bin/rt_sigsuspend01
./test-ltp.sh /ltp/testcases/bin/sbrk01
./test-ltp.sh ltp/testcases/bin/sbrk02
./test-ltp.sh ltp/testcases/bin/sched_get_priority_max01
./test-ltp.sh ltp/testcases/bin/sched_get_priority_max02
./test-ltp.sh ltp/testcases/bin/sched_get_priority_min01
./test-ltp.sh ltp/testcases/bin/sched_get_priority_min02
./test-ltp.sh ltp/testcases/bin/sched_getparam03
./test-ltp.sh ltp/testcases/bin/sched_getscheduler01
./test-ltp.sh ltp/testcases/bin/sched_getscheduler02
./test-ltp.sh ltp/testcases/bin/sched_rr_get_interval01
./test-ltp.sh ltp/testcases/bin/sched_rr_get_interval02
./test-ltp.sh ltp/testcases/bin/sched_rr_get_interval03
./test-ltp.sh ltp/testcases/bin/sched_setparam01
./test-ltp.sh ltp/testcases/bin/sched_setparam02
./test-ltp.sh ltp/testcases/bin/sched_setparam03
./test-ltp.sh ltp/testcases/bin/sched_setparam04
./test-ltp.sh ltp/testcases/bin/sched_setscheduler01
./test-ltp.sh ltp/testcases/bin/sched_tc2
./test-ltp.sh ltp/testcases/bin/sched_tc3
./test-ltp.sh ltp/testcases/bin/sched_tc4
./test-ltp.sh ltp/testcases/bin/sched_tc5
./test-ltp.sh ltp/testcases/bin/sched_yield01
./test-ltp.sh ltp/testcases/bin/semctl03
./test-ltp.sh ltp/testcases/bin/semctl05
./test-ltp.sh ltp/testcases/bin/semctl07
./test-ltp.sh ltp/testcases/bin/semget01
./test-ltp.sh ltp/testcases/bin/semop01
./test-ltp.sh /ltp/testcases/bin/send02
./test-ltp.sh ltp/testcases/bin/sendfile02
./test-ltp.sh ltp/testcases/bin/sendfile02_64
./test-ltp.sh ltp/testcases/bin/sendfile03
./test-ltp.sh ltp/testcases/bin/sendfile03_64
./test-ltp.sh ltp/testcases/bin/sendfile04
./test-ltp.sh ltp/testcases/bin/sendfile04_64
./test-ltp.sh ltp/testcases/bin/sendfile05
./test-ltp.sh ltp/testcases/bin/sendfile05_64
./test-ltp.sh ltp/testcases/bin/sendfile06
./test-ltp.sh ltp/testcases/bin/sendfile06_64
./test-ltp.sh ltp/testcases/bin/sendfile08
./test-ltp.sh ltp/testcases/bin/sendfile08_64
./test-ltp.sh ltp/testcases/bin/sendmmsg01
./test-ltp.sh ltp/testcases/bin/sendmmsg02
./test-ltp.sh ltp/testcases/bin/set_robust_list01
./test-ltp.sh ltp/testcases/bin/set_tid_address01
./test-ltp.sh ltp/testcases/bin/setdomainname01
./test-ltp.sh ltp/testcases/bin/setdomainname02
./test-ltp.sh ltp/testcases/bin/setfsuid02
./test-ltp.sh ltp/testcases/bin/setgid01
./test-ltp.sh ltp/testcases/bin/setgroups01
./test-ltp.sh ltp/testcases/bin/setgroups02
./test-ltp.sh ltp/testcases/bin/sethostname01
./test-ltp.sh ltp/testcases/bin/sethostname02
./test-ltp.sh ltp/testcases/bin/setitimer02
./test-ltp.sh ltp/testcases/bin/setpgid01
./test-ltp.sh ltp/testcases/bin/setpgid02
./test-ltp.sh ltp/testcases/bin/setpgrp01
./test-ltp.sh ltp/testcases/bin/setregid01
./test-ltp.sh ltp/testcases/bin/setregid04
./test-ltp.sh ltp/testcases/bin/setresgid02
./test-ltp.sh ltp/testcases/bin/setresuid01
./test-ltp.sh ltp/testcases/bin/setresuid03
./test-ltp.sh ltp/testcases/bin/setreuid01
./test-ltp.sh ltp/testcases/bin/setrlimit03
./test-ltp.sh ltp/testcases/bin/setrlimit04
./test-ltp.sh ltp/testcases/bin/setsid01
./test-ltp.sh ltp/testcases/bin/setsockopt01
./test-ltp.sh ltp/testcases/bin/setsockopt03
./test-ltp.sh ltp/testcases/bin/setsockopt04
./test-ltp.sh ltp/testcases/bin/settimeofday02
./test-ltp.sh ltp/testcases/bin/setuid01
./test-ltp.sh ltp/testcases/bin/setxattr02
./test-ltp.sh ltp/testcases/bin/shmat01
./test-ltp.sh ltp/testcases/bin/shmat03
./test-ltp.sh ltp/testcases/bin/shmctl03
./test-ltp.sh ltp/testcases/bin/shmctl07
./test-ltp.sh ltp/testcases/bin/shmctl08
./test-ltp.sh ltp/testcases/bin/shmdt02
./test-ltp.sh ltp/testcases/bin/shmt02
./test-ltp.sh ltp/testcases/bin/shmt03
./test-ltp.sh ltp/testcases/bin/shmt04
./test-ltp.sh ltp/testcases/bin/shmt06
./test-ltp.sh ltp/testcases/bin/shmt07
./test-ltp.sh ltp/testcases/bin/shmt08
./test-ltp.sh ltp/testcases/bin/sigaction01
./test-ltp.sh ltp/testcases/bin/sigaction02
./test-ltp.sh ltp/testcases/bin/sigaltstack01
./test-ltp.sh ltp/testcases/bin/sigaltstack02
./test-ltp.sh ltp/testcases/bin/signal02
./test-ltp.sh ltp/testcases/bin/signal03
./test-ltp.sh ltp/testcases/bin/signal04
./test-ltp.sh ltp/testcases/bin/signal05
./test-ltp.sh /ltp/testcases/bin/signalfd01
./test-ltp.sh /ltp/testcases/bin/sigprocmask01
./test-ltp.sh /ltp/testcases/bin/sigsuspend01
./test-ltp.sh ltp/testcases/bin/sigwait01
./test-ltp.sh /ltp/testcases/bin/smack_common.sh
./test-ltp.sh ltp/testcases/bin/socket02
./test-ltp.sh ltp/testcases/bin/socketpair01
./test-ltp.sh ltp/testcases/bin/socketpair02
./test-ltp.sh ltp/testcases/bin/splice03
./test-ltp.sh ltp/testcases/bin/stack_space
./test-ltp.sh ltp/testcases/bin/stat02
./test-ltp.sh ltp/testcases/bin/stat02_64
./test-ltp.sh ltp/testcases/bin/statvfs02
./test-ltp.sh ltp/testcases/bin/statx03
./test-ltp.sh /ltp/testcases/bin/stream01
./test-ltp.sh /ltp/testcases/bin/stream02
./test-ltp.sh /ltp/testcases/bin/stream03
./test-ltp.sh /ltp/testcases/bin/stream04
./test-ltp.sh /ltp/testcases/bin/stream05
./test-ltp.sh /ltp/testcases/bin/stress
./test-ltp.sh /ltp/testcases/bin/string01
./test-ltp.sh /ltp/testcases/bin/symlink02
./test-ltp.sh /ltp/testcases/bin/sync_file_range01
./test-ltp.sh /ltp/testcases/bin/syscall01
./test-ltp.sh /ltp/testcases/bin/sysinfo01
./test-ltp.sh /ltp/testcases/bin/sysinfo02
./test-ltp.sh /ltp/testcases/bin/tee02
./test-ltp.sh /ltp/testcases/bin/time-schedule
./test-ltp.sh /ltp/testcases/bin/time01
./test-ltp.sh /ltp/testcases/bin/timer_create01
./test-ltp.sh /ltp/testcases/bin/timer_create02
./test-ltp.sh /ltp/testcases/bin/timer_create03
./test-ltp.sh /ltp/testcases/bin/timer_delete01
./test-ltp.sh /ltp/testcases/bin/timer_delete02
./test-ltp.sh /ltp/testcases/bin/timer_getoverrun01
./test-ltp.sh /ltp/testcases/bin/timer_gettime01
./test-ltp.sh /ltp/testcases/bin/timer_settime02
./test-ltp.sh /ltp/testcases/bin/timerfd04
./test-ltp.sh /ltp/testcases/bin/timerfd_create01
./test-ltp.sh /ltp/testcases/bin/timerfd_gettime01
./test-ltp.sh /ltp/testcases/bin/timerfd_settime01
./test-ltp.sh /ltp/testcases/bin/tkill01
./test-ltp.sh /ltp/testcases/bin/tkill02
./test-ltp.sh /ltp/testcases/bin/times01
./test-ltp.sh /ltp/testcases/bin/truncate02
./test-ltp.sh /ltp/testcases/bin/truncate02_64
./test-ltp.sh /ltp/testcases/bin/tst_exit
./test-ltp.sh /ltp/testcases/bin/tst_ncpus
./test-ltp.sh /ltp/testcases/bin/tst_ncpus_conf
./test-ltp.sh /ltp/testcases/bin/tst_ncpus_max
./test-ltp.sh /ltp/testcases/bin/ulimit01
./test-ltp.sh /ltp/testcases/bin/uname01
./test-ltp.sh /ltp/testcases/bin/uname02
./test-ltp.sh /ltp/testcases/bin/uname04
./test-ltp.sh /ltp/testcases/bin/unlink05
./test-ltp.sh /ltp/testcases/bin/unlink07
./test-ltp.sh /ltp/testcases/bin/unlinkat01
./test-ltp.sh /ltp/testcases/bin/utsname01
./test-ltp.sh /ltp/testcases/bin/vmsplice02
./test-ltp.sh /ltp/testcases/bin/vmsplice03
./test-ltp.sh /ltp/testcases/bin/wait01
./test-ltp.sh /ltp/testcases/bin/wait02
./test-ltp.sh /ltp/testcases/bin/wait401
./test-ltp.sh /ltp/testcases/bin/wait402
./test-ltp.sh /ltp/testcases/bin/waitid02
./test-ltp.sh /ltp/testcases/bin/waitid03
./test-ltp.sh /ltp/testcases/bin/waitid05
./test-ltp.sh /ltp/testcases/bin/waitid06
./test-ltp.sh /ltp/testcases/bin/waitid09
./test-ltp.sh /ltp/testcases/bin/waitpid01
./test-ltp.sh /ltp/testcases/bin/waitpid03
./test-ltp.sh /ltp/testcases/bin/waitpid04
./test-ltp.sh /ltp/testcases/bin/write01
./test-ltp.sh /ltp/testcases/bin/write06
./test-ltp.sh /ltp/testcases/bin/writetest
./test-ltp.sh /ltp/testcases/bin/writev01
./test-ltp.sh /ltp/testcases/bin/writev02
./test-ltp.sh /ltp/testcases/bin/writev05
./test-ltp.sh /ltp/testcases/bin/writev06
