[package]
name = "driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
arch = { path = "../arch/" }
config = { path = "../config/" }
sync = { path = "../modules/sync/" }
memory = { path = "../modules/memory/" }
systype = { path = "../modules/systype/" }

log = "0.4"
spin = { version = "0.9", features = ["lazy"] }
virtio-drivers = { version = "0.7" }
