[package]
name = "systype"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
time = { path = "../time/" }

strum = { version = "0.26", default_features = false, features = ["derive"] }
