[package]
name = "user_lib"
version = "0.1.0"
edition = "2018"

[dependencies]
buddy_system_allocator = "0.9"
bitflags = "2.4"
time = { path = "../modules/time/" }
signal = { path = "../modules/signal/" }


[features]
preliminary = []
