//! # Syscall numbers
//!
//! Syscall numbers from <asm-generic/unistd.h>.

#![allow(unused)]

use strum::FromRepr;

#[derive(FromRepr, Clone, Copy, Debug, Eq, PartialEq)]
#[repr(usize)]
#[allow(non_camel_case_types)]
pub enum SyscallNo {
    GETCWD = 17,
    DUP = 23,
    DUP3 = 24,
    FCNTL = 25,
    IOCTL = 29,
    MKNOD = 33,
    MKDIR = 34,
    UNLINKAT = 35,
    UMOUNT2 = 39,
    MOUNT = 40,
    STATFS = 43,
    FTRUNCATE = 46,
    FACCESSAT = 48,
    CHDIR = 49,
    FCHMODAT = 53,
    OPENAT = 56,
    CLOSE = 57,
    PIPE2 = 59,
    GETDENTS64 = 61,
    LSEEK = 62,
    READ = 63,
    WRITE = 64,
    READV = 65,
    WRITEV = 66,
    PREAD64 = 67,
    PWRITE64 = 68,
    SENDFILE = 71,
    PSELECT6 = 72,
    PPOLL = 73,
    READLINKAT = 78,
    FSTATAT = 79,
    FSTAT = 80,
    SYNC = 81,
    FSYNC = 82,
    UTIMENSAT = 88,
    EXIT = 93,
    EXIT_GROUP = 94,
    SET_TID_ADDRESS = 96,
    FUTEX = 98,
    SET_ROBUST_LIST = 99,
    GET_ROBUST_LIST = 100,
    NANOSLEEP = 101,
    GETITIMER = 102,
    SETITIMER = 103,
    CLOCK_SETTIME = 112,
    CLOCK_GETTIME = 113,
    CLOCK_GETRES = 114,
    CLOCK_NANOSLEEP = 115,
    SYSLOG = 116,
    SCHED_SETSCHEDULER = 119,
    SCHED_GETSCHEDULER = 120,
    SCHED_GETPARAM = 121,
    SCHED_SETAFFINITY = 122,
    SCHED_GETAFFINITY = 123,
    SCHED_YIELD = 124,
    KILL = 129,
    TKILL = 130,
    TGKILL = 131,
    RT_SIGSUSPEND = 133,
    RT_SIGACTION = 134,
    RT_SIGPROCMASK = 135,
    RT_SIGTIMEDWAIT = 137,
    RT_SIGRETURN = 139,
    TIMES = 153,
    SETPGID = 154,
    GETPGID = 155,
    SETSID = 157,
    UNAME = 160,
    GETRUSAGE = 165,
    UMASK = 166,
    GETTIMEOFDAY = 169,
    GETPID = 172,
    GETPPID = 173,
    GETUID = 174,
    GETEUID = 175,
    GETGID = 176,
    GETEGID = 177,
    GETTID = 178,
    SYSINFO = 179,
    SHMGET = 194,
    SHMCTL = 195,
    SHMAT = 196,
    SHMDT = 197,
    SOCKET = 198,
    SOCKETPAIR = 199,
    BIND = 200,
    LISTEN = 201,
    ACCEPT = 202,
    CONNECT = 203,
    GETSOCKNAME = 204,
    GETPEERNAME = 205,
    SENDTO = 206,
    RECVFROM = 207,
    SETSOCKOPT = 208,
    GETSOCKOPT = 209,
    SHUTDOWN = 210,
    BRK = 214,
    MUNMAP = 215,
    CLONE = 220,
    EXECVE = 221,
    MMAP = 222,
    MPROTECT = 226,
    MSYNC = 227,
    MADVISE = 233,
    WAIT4 = 260,
    PRLIMIT64 = 261,
    RENAMEAT2 = 276,
    GETRANDOM = 278,
    MEMBARRIER = 283,
    COPY_FILE_RANGE = 285,
}

impl core::fmt::Display for SyscallNo {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        write!(f, "{}", self.as_str())
    }
}

impl SyscallNo {
    pub const fn as_str(&self) -> &'static str {
        use self::SyscallNo::*;
        match self {
            GETCWD => "getcwd",
            DUP => "dup",
            DUP3 => "dup3",
            FCNTL => "fcntl",
            IOCTL => "ioctl",
            MKNOD => "mknod",
            MKDIR => "mkdir",
            UNLINKAT => "unlinkat",
            UMOUNT2 => "umount2",
            MOUNT => "mount",
            STATFS => "statfs",
            FTRUNCATE => "ftruncate",
            FACCESSAT => "faccessat",
            CHDIR => "chdir",
            FCHMODAT => "fchmodat",
            OPENAT => "openat",
            CLOSE => "close",
            PIPE2 => "pipe2",
            GETDENTS64 => "getdents64",
            LSEEK => "lseek",
            READ => "read",
            WRITE => "write",
            READV => "readv",
            WRITEV => "writev",
            PREAD64 => "pread64",
            PWRITE64 => "pwrite64",
            SENDFILE => "sendfile",
            PSELECT6 => "pselect6",
            PPOLL => "ppoll",
            READLINKAT => "readlinkat",
            FSTATAT => "fstatat",
            FSTAT => "fstat",
            SYNC => "sync",
            FSYNC => "fsync",
            UTIMENSAT => "utimensat",
            EXIT => "exit",
            EXIT_GROUP => "exit_group",
            SET_TID_ADDRESS => "set_tid_address",
            FUTEX => "futex",
            SET_ROBUST_LIST => "set_robust_list",
            GET_ROBUST_LIST => "get_robust_list",
            NANOSLEEP => "nanosleep",
            GETITIMER => "getitimer",
            SETITIMER => "setitimer",
            CLOCK_SETTIME => "clock_settime",
            CLOCK_GETTIME => "clock_gettime",
            CLOCK_GETRES => "clock_getres",
            CLOCK_NANOSLEEP => "clock_nanosleep",
            SYSLOG => "syslog",
            SCHED_SETSCHEDULER => "sched_setscheduler",
            SCHED_GETSCHEDULER => "sched_getscheduler",
            SCHED_GETPARAM => "sched_getparam",
            SCHED_SETAFFINITY => "sched_setaffinity",
            SCHED_GETAFFINITY => "sched_getaffinity",
            SCHED_YIELD => "sched_yield",
            KILL => "kill",
            TKILL => "tkill",
            TGKILL => "tgkill",
            RT_SIGSUSPEND => "rt_sigsuspend",
            RT_SIGACTION => "rt_sigaction",
            RT_SIGPROCMASK => "rt_sigprocmask",
            RT_SIGTIMEDWAIT => "rt_sigtimedwait",
            RT_SIGRETURN => "rt_sigreturn",
            TIMES => "times",
            SETPGID => "setpgid",
            GETPGID => "getpgid",
            SETSID => "setsid",
            UNAME => "uname",
            GETRUSAGE => "getrusage",
            UMASK => "umask",
            GETTIMEOFDAY => "gettimeofday",
            GETPID => "getpid",
            GETPPID => "getppid",
            GETUID => "getuid",
            GETEUID => "geteuid",
            GETGID => "getgid",
            GETEGID => "getegid",
            GETTID => "gettid",
            SYSINFO => "sysinfo",
            SHMGET => "shmget",
            SHMCTL => "shmctl",
            SHMAT => "shmat",
            SHMDT => "shmdt",
            SOCKET => "socket",
            SOCKETPAIR => "socketpair",
            BIND => "bind",
            LISTEN => "listen",
            ACCEPT => "accept",
            CONNECT => "connect",
            GETSOCKNAME => "getsockname",
            GETPEERNAME => "getpeername",
            SENDTO => "sendto",
            RECVFROM => "recvfrom",
            SETSOCKOPT => "setsockopt",
            GETSOCKOPT => "getsockopt",
            SHUTDOWN => "shutdown",
            BRK => "brk",
            MUNMAP => "munmap",
            CLONE => "clone",
            EXECVE => "execve",
            MMAP => "mmap",
            MPROTECT => "mprotect",
            MSYNC => "msync",
            MADVISE => "madvise",
            WAIT4 => "wait4",
            PRLIMIT64 => "prlimit64",
            RENAMEAT2 => "renameat2",
            GETRANDOM => "getrandom",
            MEMBARRIER => "membarrier",
            COPY_FILE_RANGE => "copy_file_range",
        }
    }
}
